// Generated by CoffeeScript 1.7.1
(function() {
  window.Hoge = (function() {
    function Hoge(options) {
      this.header = options.$header;
      this.target = options.$target;
      this.position = options.position;
      this.type = options.moveaction;
      this.targetThrough = optinos.through;
      this.window = $(window);
      this.existing = false;
      this.animating = false;
      this.lastPosition = this.window.scrollTop();
      this.latestPosition = this.window.scrollTop();
      this.showParams;
      this.hideParams;
    }

    return Hoge;

  })();

}).call(this);
